name: Status-checks
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: TFLint
        uses: docker://wata727/tflint


  fmt:
    name: Code Format
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@master
      - run: |
          terraform fmt --recursive -check=true

  docs:
    name: Pre-Commit-Hook
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Deps
        run: |
          brew install pre-commit terraform-docs terraform tflint
      - name: Check All Files
        run: |
          terraform init
          pre-commit run --all-files
